name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: public
    - run: |
        rm -rf public/*
        rm -rf public/.org-timestamps
        docker run --rm -v $(pwd):/blog jcouyang/orgpress
        cd public
        git add .
        git config user.email "oyanglulu@gmail.com"
        git config user.name "orgpress"
        git commit -m "orgpress publish"
        git push origin gh-pages
